### ISSUE TITLE
Build failed on ios: Undefined symbol for libRNVideoHelper.a

### ISSUE THREAD

**Issue by triasrahman** [classapp/react-native-video-helper#1]
I already linked and these libraries are shown on Xcode.

![image](https://user-images.githubusercontent.com/7110859/47999789-2fb9f600-e136-11e8-8cc6-6b7e82498e07.png)

![image](https://user-images.githubusercontent.com/7110859/47999803-37799a80-e136-11e8-9c57-60e23d66d55c.png)

But the output is:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SDAVAssetExportSession", referenced from:
      objc-class-ref in libRNVideoHelper.a(RNVideoHelper.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



** BUILD FAILED **

```

macOS Mojave 10.14
Xcode 10.4

**Comment by samin** [comment]
@triasrahman fixed in 1.0.4
