### ISSUE TITLE
Missing required attribute 'authors' for RN61.2

### ISSUE THREAD

**Issue by enigmablue** [classapp/react-native-video-helper#15]
Hi no matter how i try to pod install, i keep getting this error

[!] The `react-native-video-helper` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `authors`.

==
The pod.spec does contain the s.authors but it just dosen't seem to be picked up.
Anyone else having this issue?

I'm on 
react-native-video-helper 1.4.2
React Native 61.2, Xcode 10, Node 10

**Comment by IbrahimKhanLughmani** [comment]
Yes I am also having the same problem
The `RNDeviceInfo` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | source: Git sources should specify a tag.
    - WARN  | github_sources: Github repositories should end in `.git`.
