### ISSUE TITLE
The speed of compressing the video is slower than whatsapp and hike.

### ISSUE THREAD

**Issue by Moonubanna** [classapp/react-native-video-helper#21]
Hello,
When I compressed the 500 MB video, it took 2 to 3 minutes, which is much more than the compression of Whatsapp and Hicke. So for this I should do, please help me. I want to increase the speed of compressing.

Thanks
Praveen Singh
praveen36singh@gmail.com

**Comment by gbferreira** [comment]
Hii, thanks for reporting :D  #10
