### ISSUE TITLE
Android - build failing - verify release resources

### ISSUE THREAD

**Issue by Sultanyaron** [classapp/react-native-video-helper#25]
Im facing an issue when building the app running:
./gradlew assembleRelease

react-native: 0.61.5

Auto linked (running react-native link)

getting the following error:

Execution failed for task ':react-native-video-helper:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/1870529b191e129dcae060f8b8901363/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/1870529b191e129dcae060f8b8901363/appcompat-1.0.2/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/1870529b191e129dcae060f8b8901363/appcompat-1.0.2/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/1870529b191e129dcae060f8b8901363/appcompat-1.0.2/res/values-v28/values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/1870529b191e129dcae060f8b8901363/appcompat-1.0.2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/startX not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/startY not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/endX not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/endY not found.

     /Users/eladzucker/.gradle/caches/transforms-2/files-2.1/68652175bc77f19aff659aba9568948c/core-1.0.1/res/values/values.xml:126:5-132:25: AAPT: error: resource android:attr/offset not found.

**Comment by sajaddp** [comment]
I have the same problem

**Comment by rajngarg** [comment]
Hello @samin , I am also having the same issue
btw very useful module
