### ISSUE TITLE
sound doesn't work after the compression is applied to the video

### ISSUE THREAD

**Issue by umair-dpl** [classapp/react-native-video-helper#32]
hi all,

I am facing an issue where the sound of the video doesn't work for android, how can I make this work ?

waiting for answers desperately.

**Comment by gbferreira** [comment]
Thanks for reporting. https://github.com/classapp/react-native-video-helper/issues/14

**Comment by umair-dpl** [comment]
#14 is not the solution, There is still a problem and I cannot use this library, what I have to change exactly ? @gbferreira
