### ISSUE TITLE
RN Linking

### ISSUE THREAD

**Issue by GrishovAleksei** [classapp/react-native-video-helper#34]
_react-native link react-native-video-helper_

=>

> **warn** Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
> Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
> (node:3000) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> **error** Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. 
> Run CLI with --verbose flag for more details.

So, I run  _yarn add react-native-video-helper_ 
And then I run  ...android>  _.\gradlew build_   I get

> Task :app:compileDebugJavaWithJavac FAILED
C:\projects\..\android\app\src\main\java\com\..\MainApplication.java:11: error: package com.reactlibrary does not exist
import com.reactlibrary.RNVideoHelperPackage;
                       ^
Note: C:\projects\..\android\app\src\debug\java\com\..\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 25s

**What should I do?**

**Comment by petrbela** [comment]
If you're using React Native >= 0.60, you don't need to (read: should not) call `react-native link react-native-video-helper`.

Instead, just run:
1. `yarn add react-native-video-helper`
2. `npx pod-install`

After that, you should be able to build in Xcode / Android Studio.

**Comment by gbferreira** [comment]
This bug already has been solved.
