### ISSUE TITLE
Camera roll issue on iOS

### ISSUE THREAD

**Issue by sm2017** [classapp/react-native-video-helper#9]
![image](https://user-images.githubusercontent.com/19644997/65494451-bf3cd480-dec1-11e9-8562-e026b135ce52.png)

Are you support ph:// ?

**Comment by meiqi1992** [comment]
+1 same issue

**Comment by GuoJiKaiHehe** [comment]
+1 same issue

**Comment by olanMbakop** [comment]
+1 same issue

**Comment by robban** [comment]
Is this related to live photos?

**Comment by gbferreira** [comment]
thanks for reporting !! The same #3.

**Comment by FernandesTeu** [comment]
@sm2017 did you find a solution for your problem? I'm getting the same here
